#!/bin/bash

# Date and time of report generation
CURRENT_DATETIME=$(date +"%Y-%m-%d %H:%M:%S")

# System Information
HOSTNAME_NAME=$(hostname)
OS_DESCRIPTION=$(lsb_release -d | awk -F: '{print $2}' | sed 's/^ *//g')
SYSTEM_UPTIME=$(uptime -p)

# Hardware Information
CPU_MODEL=$(lscpu | grep "Model name" | awk -F: '{print $2}' | sed 's/^ *//g')
RAM_SIZE=$(free -h | grep "Mem" | awk '{print $2}')
DISK_DETAILS=$(lsblk -d -o NAME,SIZE,MODEL | grep -v "loop" | awk '{print $1 " " $2 " " $3}')
VIDEO_CARD=$(lspci | grep -i vga | awk -F: '{print $2}' | sed 's/^ *//g')

# Network Information
FQDN_NAME=$(hostname -f)
HOST_IP_ADDRESS=$(ip addr show | grep "inet " | grep -v "127.0.0.1" | awk '{print $2}' | cut -d/ -f1 | head -n 1)
DEFAULT_GATEWAY=$(ip route show default | awk '{print $3}')
DNS_SERVER_IP=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | head -n 1)

# System Status Information
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
LOCAL_DISK_SPACE=$(df -h | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{print $6 " " $4}')
PROCESS_COUNT=$(ps aux | wc -l)
SYSTEM_LOAD=$(uptime | awk -F'load average:' '{ print $2 }' | sed 's/^ *//g')
LISTENING_PORT_COUNT=$(ss -tuln | grep -v "State" | grep -c "")
UFW_STATUS=$(sudo ufw status | head -n 1 | awk '{print $2}')

# Generating the final report
cat <<EOF

System Report generated by $USER, $CURRENT_DATETIME

System Information
------------------
Hostname: $HOSTNAME_NAME
OS: $OS_DESCRIPTION
Uptime: $SYSTEM_UPTIME

Hardware Information
--------------------
CPU: $CPU_MODEL
Ram: $RAM_SIZE
Disk(s): $DISK_DETAILS
Video: $VIDEO_CARD

Network Information
-------------------
FQDN: $FQDN_NAME
Host Address: $HOST_IP_ADDRESS
Gateway IP: $DEFAULT_GATEWAY
DNS Server: $DNS_SERVER_IP

System Status
-------------
Users Logged In: $LOGGED_IN_USERS
Disk Space: $LOCAL_DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $SYSTEM_LOAD
Listening Network Ports: $LISTENING_PORT_COUNT
UFW Status: $UFW_STATUS

EOF
